/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Models.AbsorbentModel;
import Models.DirectModel;
import javax.swing.JFrame;

/**
 *
 * @author jf_me
 */
public class Main extends javax.swing.JFrame {
    private DirectModel dmod;
    private AbsorbentModel amod;
    /**
     * Creates new form Main
     */
    public Main() {
        dmod=new DirectModel();
        amod=new AbsorbentModel();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        direct = new javax.swing.JScrollPane();
        tabdirect = new javax.swing.JTable();
        absorbent = new javax.swing.JScrollPane();
        tababsorbent = new javax.swing.JTable();
        btnpane = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        TabPane = new javax.swing.JTabbedPane();
        mainmn = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        tabdirect.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        direct.setViewportView(tabdirect);

        tababsorbent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        absorbent.setViewportView(tababsorbent);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRO Accounting");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setText("Insertar Datos");
        btnpane.add(jButton1);

        getContentPane().add(btnpane, java.awt.BorderLayout.PAGE_END);

        TabPane.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        getContentPane().add(TabPane, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Archivo");
        mainmn.add(jMenu1);

        jMenu2.setText("Opciones");
        mainmn.add(jMenu2);

        setJMenuBar(mainmn);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        TabPane.addTab("Costeo Directo", null, direct, "Estado de resultados por costeo directo");
        TabPane.addTab("Costeo Absorbente", null, absorbent, "Estado de resultados por costeo absorbente");
        tabdirect.setModel(dmod.getModel());
        tababsorbent.setModel(amod.getModel());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabPane;
    private javax.swing.JScrollPane absorbent;
    private javax.swing.JPanel btnpane;
    private javax.swing.JScrollPane direct;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar mainmn;
    private javax.swing.JTable tababsorbent;
    private javax.swing.JTable tabdirect;
    // End of variables declaration//GEN-END:variables
}
